"""
config.py – Shared configuration for all automation scripts.
Reads values from .env at the project root, and reads the reporting
period (month/year/day range) + RUN_ID from environment variables so a
GitHub Actions workflow_dispatch run can target any month/date instead
of always running for "today".
"""

import os
import calendar
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# ── Root dir ──────────────────────────────────────────────────────────────────
ROOT_DIR = Path(__file__).resolve().parent.parent

load_dotenv(ROOT_DIR / ".env")

# ── Paths ─────────────────────────────────────────────────────────────────────
DOWNLOAD_DIR = str(ROOT_DIR / "downloads")

# ── BK Portal Credentials ─────────────────────────────────────────────────────
BK_USERNAME = os.getenv("BK_USERNAME", "")
BK_PASSWORD = os.getenv("BK_PASSWORD", "")

# ── Denny's Credentials ────────────────────────────────────────────────────────
DS_USERNAME = os.getenv("DS_USERNAME", "")
DS_PASSWORD = os.getenv("DS_PASSWORD", "")

# ── Reporting period ───────────────────────────────────────────────────────────
# These are set by the GitHub Actions workflow_dispatch inputs (see
# .github/workflows/*.yml). If they're missing (e.g. running locally),
# everything falls back to "this month" like the scripts used to behave.
_today = datetime.now()

TARGET_YEAR = int(os.getenv("TARGET_YEAR", _today.year))
TARGET_MONTH = int(os.getenv("TARGET_MONTH", _today.month))

_is_current_month = (TARGET_YEAR, TARGET_MONTH) == (_today.year, _today.month)
_last_day_of_month = calendar.monthrange(TARGET_YEAR, TARGET_MONTH)[1]

# Day range within the target month (used by dennys.py for its date picker).
# Empty-string env vars (GitHub Actions optional workflow_dispatch inputs with
# no value supplied) are treated the same as "not set".
_raw_from_day = os.getenv("DATE_FROM_DAY", "").strip()
_raw_to_day = os.getenv("DATE_TO_DAY", "").strip()

DATE_FROM_DAY = int(_raw_from_day) if _raw_from_day else 1
DATE_TO_DAY = int(_raw_to_day) if _raw_to_day else (
    _today.day if _is_current_month else _last_day_of_month
)

# Human-readable "Mon YYYY" label used to find the right scorecard tile on
# the BK insights dashboard (e.g. "Jul 2026").
TARGET_MONTH_LABEL = datetime(TARGET_YEAR, TARGET_MONTH, 1).strftime("%b %Y")

# ── Run tagging ─────────────────────────────────────────────────────────────
# Unique id passed in by the triggering workflow_dispatch call (generated by
# the frontend). Appended to final output filenames so the frontend can find
# the right file on the Test Records API once the run finishes. Falls back
# to a period-based tag so scripts still work if run manually/locally.
RUN_ID = os.getenv("RUN_ID", f"{TARGET_YEAR}{TARGET_MONTH:02d}-local")

# ── Restaurant Mappings ───────────────────────────────────────────────────────
RESTAURANT_MAPPING = {
    16348: "St. Johns",
    16620: "Teravista BK",
    16678: "Jarrell BK",
    18358: "Montopolis BK",
    20533: "Live OaK BK",
    21221: "Wells Branch BK",
    21516: "MLK BK",
    24603: "Taylor BK",
    24814: "Bastrop BK",
    24916: "San Antonio Airport BK",
    25783: "Leander BK",
    26752: "TECHRIDGE",
    27134: "Potranco BK",
    28502: "Elgin BK",
}

MANAGER_MAPPING = {
    16348: "Ismael Camacho",
    16620: "Jose Esquivel",
    16678: "Jose Esquivel",
    18358: "Ismael Camacho",
    20533: "Ismael Camacho",
    21221: "Jose Esquivel",
    21516: "Ismael Camacho",
    24603: "Jose Esquivel",
    24814: "Jose Esquivel",
    24916: "Ismael Camacho",
    25783: "Ismael Camacho",
    26752: "Ismael Camacho",
    27134: "Ismael Camacho",
    28502: "Jose Esquivel",
}

# ── Restaurant data list (used by reviewsparser) ──────────────────────────────
RESTAURANT_DATA = [
    (str(rid), name, MANAGER_MAPPING[rid])
    for rid, name in RESTAURANT_MAPPING.items()
]
